version: '3.8'
services:
  init-data:   
    image: alpine
    volumes:
      - app-data:/data
      - ./app/data:/source
    command: sh -c "mkdir -p /source /data && cp /source/* /data/"
    deploy:
      restart_policy:
        condition: none
    
  app:          
    build: .
    ports:
      - "8001:8000"
    volumes:
      - app-data:/data
    depends_on:
      - init-data

volumes:        
  app-data: