version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data 
    environment:
      - DATASET_PATH=/data/openfoodfacts_sample.pkl
      - SIMILARITIES_PATH=/data/similarities.csv
      - MODEL_CACHE_SIZE=75
      - MEMORY_LIMIT=4g
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  dataset_volume:
    driver: local
    driver_opts:
      type: none
      device: ./data  
      o: bind